spring:
  application:
    name: weather-kotlin
#  mail:
#    default-encoding: UTF-8
#    host: smtp.gmail.com
#    port: 465
#    username: ""
#    password: ""
  datasource:
    driverClassName: org.sqlite.JDBC
    url: "jdbc:sqlite:src/main/resources/Weather.db"
    username: ""
    password: ""
  jpa:
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLiteDialect
  main:
    banner-mode: off

server:
  port: 8091

city: ""
key: ""