spring:
  application:
    name: weather-kotlin
  datasource:
    driverClassName: org.sqlite.JDBC
    url: "jdbc:sqlite:/home/viacheslav/IdeaProjects/weather-kotlin/src/main/resources/Weather.db"
    username: ""
    password: ""
  jpa:
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLiteDialect
  main:
    banner-mode: off

city: "Rostov-on-Don"
key: "ad9c2421aa366de44dcbdc0ce43419d7"